"""create recurring_transactions table, add source to transactions

Revision ID: 5794659919a8
Revises: b6be3270c643
Create Date: 2026-09-19 00:33:03.477936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5794659919a8'
down_revision: Union[str, Sequence[str], None] = 'b6be3270c643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('type', postgresql.ENUM('INCOME', 'EXPENSE', name='transaction_type', create_type=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.Enum('WEEKLY', 'MONTHLY', name='recurring_frequency'), nullable=False),
    sa.Column('next_occurrence_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_transactions_account_id'), 'recurring_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_category_id'), 'recurring_transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_user_id'), 'recurring_transactions', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('recurring_transaction_id', sa.Uuid(), nullable=True))
    transaction_source = postgresql.ENUM('MANUAL', 'RECURRING', 'IMPORT', name='transaction_source')
    transaction_source.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'transactions',
        sa.Column(
            'source',
            postgresql.ENUM('MANUAL', 'RECURRING', 'IMPORT', name='transaction_source', create_type=False),
            server_default='MANUAL',
            nullable=False,
        ),
    )
    op.create_index(op.f('ix_transactions_recurring_transaction_id'), 'transactions', ['recurring_transaction_id'], unique=False)
    op.create_foreign_key(
        'fk_transactions_recurring_transaction_id_recurring_transactions',
        'transactions', 'recurring_transactions', ['recurring_transaction_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_transactions_recurring_transaction_id_recurring_transactions', 'transactions', type_='foreignkey'
    )
    op.drop_index(op.f('ix_transactions_recurring_transaction_id'), table_name='transactions')
    op.drop_column('transactions', 'source')
    postgresql.ENUM(name='transaction_source').drop(op.get_bind(), checkfirst=True)
    op.drop_column('transactions', 'recurring_transaction_id')
    op.drop_index(op.f('ix_recurring_transactions_user_id'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_category_id'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_account_id'), table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    # ### end Alembic commands ###
